// ═══════════════════════════════════════════════════════════════════
// RUIL CLI — Component Registry
// Maps every supported library to its components, install strategy,
// and import patterns.
// ═══════════════════════════════════════════════════════════════════

export const LIBRARIES = {
  shadcn: {
    name: "shadcn/ui",
    strategy: "cli",            // components added via CLI
    baseCommand: "npx shadcn-ui@latest add",
    batchable: true,            // can combine: `add button card input`
    importPrefix: "@/components/ui",
    docsURL: "https://ui.shadcn.com",
    components: [
      { name: "accordion",      description: "Vertically collapsing panels" },
      { name: "alert",           description: "Callout for important messages" },
      { name: "alert-dialog",    description: "Modal confirmation dialog" },
      { name: "avatar",          description: "User profile image placeholder" },
      { name: "badge",           description: "Status/label indicator" },
      { name: "breadcrumb",      description: "Navigation trail" },
      { name: "button",          description: "Clickable action element" },
      { name: "calendar",        description: "Date picker calendar" },
      { name: "card",            description: "Container with header/content/footer" },
      { name: "carousel",        description: "Rotating content slider" },
      { name: "checkbox",        description: "Boolean toggle control" },
      { name: "collapsible",     description: "Expandable content area" },
      { name: "command",         description: "Command palette / search" },
      { name: "context-menu",    description: "Right-click contextual menu" },
      { name: "dialog",          description: "Modal overlay" },
      { name: "drawer",          description: "Slide-out side panel" },
      { name: "dropdown-menu",   description: "Click-triggered dropdown" },
      { name: "form",            description: "Form primitives with validation" },
      { name: "hover-card",      description: "Hover-triggered popover" },
      { name: "input",           description: "Text input field" },
      { name: "label",           description: "Form label element" },
      { name: "menubar",         description: "Horizontal menu bar" },
      { name: "navigation-menu", description: "Site navigation component" },
      { name: "popover",         description: "Floating content panel" },
      { name: "progress",        description: "Progress indicator bar" },
      { name: "radio-group",     description: "Single-select radio buttons" },
      { name: "scroll-area",     description: "Custom scrollable container" },
      { name: "select",          description: "Dropdown select control" },
      { name: "separator",       description: "Visual divider line" },
      { name: "sheet",           description: "Responsive side panel" },
      { name: "skeleton",        description: "Loading placeholder" },
      { name: "slider",          description: "Range input control" },
      { name: "switch",          description: "Toggle switch control" },
      { name: "table",           description: "Data table layout" },
      { name: "tabs",            description: "Tabbed content panels" },
      { name: "textarea",        description: "Multi-line text input" },
      { name: "toast",           description: "Notification toast popup" },
      { name: "toggle",          description: "Pressed/unpressed toggle" },
      { name: "tooltip",         description: "Hover hint text" },
    ],
  },

  mui: {
    name: "Material UI (MUI)",
    strategy: "npm",            // installed via npm packages
    packages: ["@mui/material", "@emotion/react", "@emotion/styled"],
    batchable: false,
    importPrefix: "@mui/material",
    docsURL: "https://mui.com/material-ui/getting-started/",
    components: [
      { name: "Accordion",       description: "Expandable panels", import: "Accordion" },
      { name: "Alert",           description: "Feedback messages", import: "Alert" },
      { name: "AppBar",          description: "Top navigation bar", import: "AppBar" },
      { name: "Autocomplete",    description: "Combo box with search", import: "Autocomplete" },
      { name: "Avatar",          description: "User image/icon", import: "Avatar" },
      { name: "Badge",           description: "Notification badge", import: "Badge" },
      { name: "BottomNavigation",description: "Mobile tab bar", import: "BottomNavigation" },
      { name: "Breadcrumbs",     description: "Navigation trail", import: "Breadcrumbs" },
      { name: "Button",          description: "Click action", import: "Button" },
      { name: "ButtonGroup",     description: "Grouped buttons", import: "ButtonGroup" },
      { name: "Card",            description: "Content container", import: "Card" },
      { name: "Checkbox",        description: "Multi-select toggle", import: "Checkbox" },
      { name: "Chip",            description: "Compact element tag", import: "Chip" },
      { name: "CircularProgress",description: "Spinner loader", import: "CircularProgress" },
      { name: "Dialog",          description: "Modal dialog", import: "Dialog" },
      { name: "Divider",         description: "Section separator", import: "Divider" },
      { name: "Drawer",          description: "Side navigation panel", import: "Drawer" },
      { name: "Fab",             description: "Floating action button", import: "Fab" },
      { name: "Grid",            description: "Layout grid system", import: "Grid" },
      { name: "IconButton",      description: "Icon-only button", import: "IconButton" },
      { name: "LinearProgress",  description: "Progress bar", import: "LinearProgress" },
      { name: "List",            description: "Vertical list", import: "List" },
      { name: "Menu",            description: "Menu dropdown", import: "Menu" },
      { name: "Modal",           description: "Modal overlay", import: "Modal" },
      { name: "Pagination",      description: "Page navigation", import: "Pagination" },
      { name: "Paper",           description: "Elevated surface", import: "Paper" },
      { name: "Radio",           description: "Single-select radio", import: "Radio" },
      { name: "Rating",          description: "Star rating input", import: "Rating" },
      { name: "Select",          description: "Dropdown select", import: "Select" },
      { name: "Skeleton",        description: "Loading placeholder", import: "Skeleton" },
      { name: "Slider",          description: "Range slider", import: "Slider" },
      { name: "Snackbar",        description: "Toast notification", import: "Snackbar" },
      { name: "Switch",          description: "Toggle switch", import: "Switch" },
      { name: "Tab",             description: "Tab navigation", import: "Tab" },
      { name: "Table",           description: "Data table", import: "Table" },
      { name: "TextField",       description: "Text input field", import: "TextField" },
      { name: "Tooltip",         description: "Hover tooltip", import: "Tooltip" },
      { name: "Typography",      description: "Text styling", import: "Typography" },
    ],
  },

  chakra: {
    name: "Chakra UI",
    strategy: "npm",
    packages: ["@chakra-ui/react", "@emotion/react", "@emotion/styled", "framer-motion"],
    batchable: false,
    importPrefix: "@chakra-ui/react",
    docsURL: "https://chakra-ui.com/docs/get-started/installation",
    components: [
      { name: "Accordion",    description: "Expandable sections", import: "Accordion" },
      { name: "Alert",        description: "Status messages", import: "Alert" },
      { name: "Avatar",       description: "User avatar", import: "Avatar" },
      { name: "Badge",        description: "Label badge", import: "Badge" },
      { name: "Box",          description: "Layout primitive", import: "Box" },
      { name: "Button",       description: "Action button", import: "Button" },
      { name: "Card",         description: "Container card", import: "Card" },
      { name: "Checkbox",     description: "Check toggle", import: "Checkbox" },
      { name: "Drawer",       description: "Side panel", import: "Drawer" },
      { name: "Flex",         description: "Flexbox layout", import: "Flex" },
      { name: "FormControl",  description: "Form wrapper", import: "FormControl" },
      { name: "Grid",         description: "Grid layout", import: "Grid" },
      { name: "Heading",      description: "Heading text", import: "Heading" },
      { name: "IconButton",   description: "Icon button", import: "IconButton" },
      { name: "Image",        description: "Image element", import: "Image" },
      { name: "Input",        description: "Text input", import: "Input" },
      { name: "Menu",         description: "Menu dropdown", import: "Menu" },
      { name: "Modal",        description: "Modal dialog", import: "Modal" },
      { name: "Progress",     description: "Progress bar", import: "Progress" },
      { name: "Radio",        description: "Radio select", import: "Radio" },
      { name: "Select",       description: "Dropdown select", import: "Select" },
      { name: "Skeleton",     description: "Loading skeleton", import: "Skeleton" },
      { name: "Slider",       description: "Range slider", import: "Slider" },
      { name: "Spinner",      description: "Loading spinner", import: "Spinner" },
      { name: "Switch",       description: "Toggle switch", import: "Switch" },
      { name: "Table",        description: "Data table", import: "Table" },
      { name: "Tabs",         description: "Tab navigation", import: "Tabs" },
      { name: "Tag",          description: "Tag label", import: "Tag" },
      { name: "Text",         description: "Body text", import: "Text" },
      { name: "Textarea",     description: "Multi-line input", import: "Textarea" },
      { name: "Toast",        description: "Notification", import: "useToast" },
      { name: "Tooltip",      description: "Hover tooltip", import: "Tooltip" },
    ],
  },

  nextui: {
    name: "NextUI",
    strategy: "npm",
    packages: ["@nextui-org/react", "framer-motion"],
    batchable: false,
    importPrefix: "@nextui-org/react",
    docsURL: "https://nextui.org/docs/guide/introduction",
    components: [
      { name: "Accordion",  description: "Collapsible panels", import: "Accordion" },
      { name: "Avatar",     description: "User avatar", import: "Avatar" },
      { name: "Badge",      description: "Status badge", import: "Badge" },
      { name: "Button",     description: "Action button", import: "Button" },
      { name: "Card",       description: "Content card", import: "Card" },
      { name: "Checkbox",   description: "Check control", import: "Checkbox" },
      { name: "Chip",       description: "Compact tag", import: "Chip" },
      { name: "Divider",    description: "Separator line", import: "Divider" },
      { name: "Dropdown",   description: "Dropdown menu", import: "Dropdown" },
      { name: "Input",      description: "Text input", import: "Input" },
      { name: "Modal",      description: "Modal dialog", import: "Modal" },
      { name: "Navbar",     description: "Navigation bar", import: "Navbar" },
      { name: "Pagination", description: "Page nav", import: "Pagination" },
      { name: "Popover",    description: "Floating panel", import: "Popover" },
      { name: "Progress",   description: "Progress bar", import: "Progress" },
      { name: "Radio",      description: "Radio group", import: "RadioGroup" },
      { name: "Select",     description: "Dropdown select", import: "Select" },
      { name: "Skeleton",   description: "Loading state", import: "Skeleton" },
      { name: "Slider",     description: "Range slider", import: "Slider" },
      { name: "Switch",     description: "Toggle switch", import: "Switch" },
      { name: "Table",      description: "Data table", import: "Table" },
      { name: "Tabs",       description: "Tab panels", import: "Tabs" },
      { name: "Textarea",   description: "Text area", import: "Textarea" },
      { name: "Tooltip",    description: "Hover tip", import: "Tooltip" },
    ],
  },

  daisyui: {
    name: "daisyUI",
    strategy: "npm-plugin",
    packages: ["daisyui"],
    devDep: true,
    batchable: false,
    importPrefix: null,         // CSS class-based, no imports
    docsURL: "https://daisyui.com/docs/install/",
    setupNote: 'Add "daisyui" to plugins array in tailwind.config.js',
    components: [
      { name: "btn",          description: "Button", className: "btn btn-primary" },
      { name: "card",         description: "Card container", className: "card" },
      { name: "navbar",       description: "Navigation bar", className: "navbar" },
      { name: "drawer",       description: "Side drawer", className: "drawer" },
      { name: "modal",        description: "Modal dialog", className: "modal" },
      { name: "alert",        description: "Alert message", className: "alert" },
      { name: "badge",        description: "Badge indicator", className: "badge" },
      { name: "collapse",     description: "Expandable section", className: "collapse" },
      { name: "dropdown",     description: "Dropdown panel", className: "dropdown" },
      { name: "menu",         description: "Menu list", className: "menu" },
      { name: "progress",     description: "Progress bar", className: "progress" },
      { name: "tabs",         description: "Tab navigation", className: "tabs" },
      { name: "table",        description: "Data table", className: "table" },
      { name: "toggle",       description: "Toggle switch", className: "toggle" },
      { name: "tooltip",      description: "Tooltip", className: "tooltip" },
      { name: "textarea",     description: "Text area input", className: "textarea" },
      { name: "input",        description: "Text input", className: "input" },
      { name: "select",       description: "Dropdown select", className: "select" },
      { name: "skeleton",     description: "Loading skeleton", className: "skeleton" },
      { name: "hero",         description: "Hero section", className: "hero" },
      { name: "footer",       description: "Footer layout", className: "footer" },
    ],
  },

  antd: {
    name: "Ant Design",
    strategy: "npm",
    packages: ["antd"],
    batchable: false,
    importPrefix: "antd",
    docsURL: "https://ant.design/docs/react/introduce",
    components: [
      { name: "Button",       description: "Action button", import: "Button" },
      { name: "Table",        description: "Data table", import: "Table" },
      { name: "Form",         description: "Form controls", import: "Form" },
      { name: "Input",        description: "Text input", import: "Input" },
      { name: "Select",       description: "Dropdown select", import: "Select" },
      { name: "Modal",        description: "Dialog modal", import: "Modal" },
      { name: "Card",         description: "Card container", import: "Card" },
      { name: "Tabs",         description: "Tab panels", import: "Tabs" },
      { name: "Menu",         description: "Navigation menu", import: "Menu" },
      { name: "Drawer",       description: "Side drawer", import: "Drawer" },
      { name: "Alert",        description: "Alert banner", import: "Alert" },
      { name: "Avatar",       description: "User avatar", import: "Avatar" },
      { name: "Badge",        description: "Notification badge", import: "Badge" },
      { name: "Breadcrumb",   description: "Navigation breadcrumb", import: "Breadcrumb" },
      { name: "Checkbox",     description: "Check control", import: "Checkbox" },
      { name: "DatePicker",   description: "Date selector", import: "DatePicker" },
      { name: "Dropdown",     description: "Dropdown menu", import: "Dropdown" },
      { name: "Layout",       description: "Page layout", import: "Layout" },
      { name: "Pagination",   description: "Page navigation", import: "Pagination" },
      { name: "Progress",     description: "Progress indicator", import: "Progress" },
      { name: "Radio",        description: "Radio select", import: "Radio" },
      { name: "Slider",       description: "Range slider", import: "Slider" },
      { name: "Spin",         description: "Loading spinner", import: "Spin" },
      { name: "Switch",       description: "Toggle switch", import: "Switch" },
      { name: "Tag",          description: "Tag label", import: "Tag" },
      { name: "Tooltip",      description: "Tooltip hint", import: "Tooltip" },
      { name: "Typography",   description: "Text typography", import: "Typography" },
      { name: "Upload",       description: "File upload", import: "Upload" },
    ],
  },

  mantine: {
    name: "Mantine UI",
    strategy: "npm",
    packages: ["@mantine/core", "@mantine/hooks"],
    batchable: false,
    importPrefix: "@mantine/core",
    docsURL: "https://mantine.dev/getting-started/",
    components: [
      { name: "Accordion",    description: "Collapsible sections", import: "Accordion" },
      { name: "ActionIcon",   description: "Icon button", import: "ActionIcon" },
      { name: "Alert",        description: "Alert message", import: "Alert" },
      { name: "Avatar",       description: "User avatar", import: "Avatar" },
      { name: "Badge",        description: "Status badge", import: "Badge" },
      { name: "Button",       description: "Action button", import: "Button" },
      { name: "Card",         description: "Content card", import: "Card" },
      { name: "Checkbox",     description: "Check control", import: "Checkbox" },
      { name: "ColorInput",   description: "Color picker", import: "ColorInput" },
      { name: "Drawer",       description: "Side drawer", import: "Drawer" },
      { name: "Grid",         description: "Grid layout", import: "Grid" },
      { name: "Input",        description: "Text input", import: "Input" },
      { name: "Menu",         description: "Menu dropdown", import: "Menu" },
      { name: "Modal",        description: "Modal dialog", import: "Modal" },
      { name: "NumberInput",  description: "Numeric input", import: "NumberInput" },
      { name: "Pagination",   description: "Page navigation", import: "Pagination" },
      { name: "Progress",     description: "Progress bar", import: "Progress" },
      { name: "Radio",        description: "Radio group", import: "Radio" },
      { name: "Select",       description: "Select dropdown", import: "Select" },
      { name: "Skeleton",     description: "Loading skeleton", import: "Skeleton" },
      { name: "Slider",       description: "Range slider", import: "Slider" },
      { name: "Switch",       description: "Toggle switch", import: "Switch" },
      { name: "Table",        description: "Data table", import: "Table" },
      { name: "Tabs",         description: "Tab panels", import: "Tabs" },
      { name: "TextInput",    description: "Text field", import: "TextInput" },
      { name: "Textarea",     description: "Multi-line input", import: "Textarea" },
      { name: "Tooltip",      description: "Hover tooltip", import: "Tooltip" },
    ],
  },
};

// Quick index: library alias → key
export const ALIASES = {
  "shadcn":    "shadcn",
  "shadcnui":  "shadcn",
  "shadcn-ui": "shadcn",
  "mui":       "mui",
  "material":  "mui",
  "materialui":"mui",
  "chakra":    "chakra",
  "chakraui":  "chakra",
  "nextui":    "nextui",
  "daisyui":   "daisyui",
  "daisy":     "daisyui",
  "antd":      "antd",
  "antdesign": "antd",
  "mantine":   "mantine",
  "mantineui": "mantine",
};

export function resolveLibrary(input) {
  const key = input.toLowerCase().replace(/[\s\-_\/]/g, "");
  return ALIASES[key] || null;
}
