// ═══════════════════════════════════════════════════════════════════
// RUIL CLI — Component Registry
// Maps every supported library to its components, install strategy,
// and import patterns.
// ═══════════════════════════════════════════════════════════════════

export const LIBRARIES = {
  shadcn: {
    name: "shadcn/ui",
    strategy: "cli",            // components added via CLI
    baseCommand: "npx shadcn-ui@latest add",
    batchable: true,
    importPrefix: "@/components/ui",
    docsURL: "https://ui.shadcn.com",
    components: [
      { name: "accordion",      description: "Collapsible panels" },
      { name: "alert",           description: "Important messages" },
      { name: "alert-dialog",    description: "Modal confirmation" },
      { name: "avatar",          description: "Profile image" },
      { name: "badge",           description: "Status indicator" },
      { name: "breadcrumb",      description: "Nav trail" },
      { name: "button",          description: "Clickable action" },
      { name: "calendar",        description: "Date picker" },
      { name: "card",            description: "Content container" },
      { name: "carousel",        description: "Content slider" },
      { name: "checkbox",        description: "Toggle control" },
      { name: "command",         description: "Command palette" },
      { name: "dialog",          description: "Modal overlay" },
      { name: "drawer",          description: "Side panel" },
      { name: "dropdown-menu",   description: "Menu dropdown" },
      { name: "form",            description: "Form primitives" },
      { name: "input",           description: "Text field" },
      { name: "label",           description: "Form label" },
      { name: "navigation-menu", description: "Site navigation" },
      { name: "popover",         description: "Floating panel" },
      { name: "progress",        description: "Progress bar" },
      { name: "scroll-area",     description: "Custom scroll" },
      { name: "select",          description: "Select dropdown" },
      { name: "separator",       description: "Visual divider" },
      { name: "sheet",           description: "Side drawer" },
      { name: "skeleton",        description: "Loading state" },
      { name: "slider",          description: "Range input" },
      { name: "switch",          description: "Toggle switch" },
      { name: "table",           description: "Data table" },
      { name: "tabs",            description: "Tabbed content" },
      { name: "textarea",        description: "Multi-line input" },
      { name: "toast",           description: "Notification" },
      { name: "tooltip",         description: "Hover hint" },
    ],
  },

  mui: {
    name: "Material UI",
    strategy: "npm",
    packages: ["@mui/material", "@emotion/react", "@emotion/styled"],
    importPrefix: "@mui/material",
    docsURL: "https://mui.com",
    components: [
      { name: "Accordion",       description: "Collapsible panels", import: "Accordion" },
      { name: "Alert",           description: "Status messages", import: "Alert" },
      { name: "AppBar",          description: "Top navigation", import: "AppBar" },
      { name: "Autocomplete",    description: "Combo box", import: "Autocomplete" },
      { name: "Avatar",          description: "User image", import: "Avatar" },
      { name: "Badge",           description: "Indicator badge", import: "Badge" },
      { name: "Box",             description: "Layout primitive", import: "Box" },
      { name: "Breadcrumbs",     description: "Nav trail", import: "Breadcrumbs" },
      { name: "Button",          description: "Click action", import: "Button" },
      { name: "Card",            description: "Content card", import: "Card" },
      { name: "Checkbox",        description: "Check toggle", import: "Checkbox" },
      { name: "Chip",            description: "Compact tag", import: "Chip" },
      { name: "Dialog",          description: "Modal dialog", import: "Dialog" },
      { name: "Divider",         description: "Separator", import: "Divider" },
      { name: "Drawer",          description: "Side panel", import: "Drawer" },
      { name: "Grid",            description: "Layout grid", import: "Grid" },
      { name: "IconButton",      description: "Icon button", import: "IconButton" },
      { name: "Input",           description: "Text input", import: "Input" },
      { name: "List",            description: "Vertical list", import: "List" },
      { name: "Menu",            description: "Dropdown menu", import: "Menu" },
      { name: "Modal",           description: "Modal overlay", import: "Modal" },
      { name: "Paper",           description: "Surface", import: "Paper" },
      { name: "Select",          description: "Select dropdown", import: "Select" },
      { name: "Slider",          description: "Range slider", import: "Slider" },
      { name: "Snackbar",        description: "Toast notification", import: "Snackbar" },
      { name: "Stack",           description: "Layout container", import: "Stack" },
      { name: "Switch",          description: "Toggle switch", import: "Switch" },
      { name: "Table",           description: "Data table", import: "Table" },
      { name: "Tabs",            description: "Tab panels", import: "Tabs" },
      { name: "TextField",       description: "Input field", import: "TextField" },
      { name: "Tooltip",         description: "Hover tip", import: "Tooltip" },
      { name: "Typography",      description: "Text styling", import: "Typography" },
    ],
  },

  chakra: {
    name: "Chakra UI",
    strategy: "npm",
    packages: ["@chakra-ui/react", "@emotion/react", "@emotion/styled", "framer-motion"],
    importPrefix: "@chakra-ui/react",
    docsURL: "https://chakra-ui.com",
    components: [
      { name: "Accordion",    description: "Collapsible items", import: "Accordion" },
      { name: "Alert",        description: "Status colors", import: "Alert" },
      { name: "Avatar",       description: "User avatar", import: "Avatar" },
      { name: "Badge",        description: "Label badge", import: "Badge" },
      { name: "Box",          description: "Layout container", import: "Box" },
      { name: "Button",       description: "Action button", import: "Button" },
      { name: "Card",         description: "Card container", import: "Card" },
      { name: "Checkbox",     description: "Check control", import: "Checkbox" },
      { name: "Container",    description: "Page container", import: "Container" },
      { name: "Drawer",       description: "Side drawer", import: "Drawer" },
      { name: "Flex",         description: "Flexbox layout", import: "Flex" },
      { name: "FormControl",  description: "Form wrapper", import: "FormControl" },
      { name: "Grid",         description: "Grid layout", import: "Grid" },
      { name: "Heading",      description: "Header text", import: "Heading" },
      { name: "Image",        description: "Responsive image", import: "Image" },
      { name: "Input",        description: "Text input", import: "Input" },
      { name: "Menu",         description: "Dropdown menu", import: "Menu" },
      { name: "Modal",        description: "Modal dialog", import: "Modal" },
      { name: "Progress",     description: "Progress bar", import: "Progress" },
      { name: "Select",       description: "Select dropdown", import: "Select" },
      { name: "Skeleton",     description: "Loading state", import: "Skeleton" },
      { name: "Slider",       description: "Range slider", import: "Slider" },
      { name: "Spinner",      description: "Loading spinner", import: "Spinner" },
      { name: "Stack",        description: "Vertical layout", import: "Stack" },
      { name: "Switch",       description: "Toggle switch", import: "Switch" },
      { name: "Table",        description: "Data table", import: "Table" },
      { name: "Tabs",         description: "Tab panels", import: "Tabs" },
      { name: "Tag",          description: "Tag element", import: "Tag" },
      { name: "Text",         description: "Body text", import: "Text" },
      { name: "Textarea",     description: "Multi-line input", import: "Textarea" },
      { name: "Tooltip",      description: "Hover hint", import: "Tooltip" },
    ],
  },

  nextui: {
    name: "NextUI",
    strategy: "npm",
    packages: ["@nextui-org/react", "framer-motion"],
    importPrefix: "@nextui-org/react",
    docsURL: "https://nextui.org",
    components: [
      { name: "Accordion",  description: "Collapsible", import: "Accordion" },
      { name: "Avatar",     description: "User image", import: "Avatar" },
      { name: "Badge",      description: "Indicator", import: "Badge" },
      { name: "Button",     description: "Action", import: "Button" },
      { name: "Card",       description: "Container", import: "Card" },
      { name: "Checkbox",   description: "Check", import: "Checkbox" },
      { name: "Chip",       description: "Tag", import: "Chip" },
      { name: "Divider",    description: "Line", import: "Divider" },
      { name: "Dropdown",   description: "Menu", import: "Dropdown" },
      { name: "Image",      description: "Picture", import: "Image" },
      { name: "Input",      description: "Input", import: "Input" },
      { name: "Kbd",        description: "Keyboard key", import: "Kbd" },
      { name: "Link",       description: "Anchor", import: "Link" },
      { name: "Modal",      description: "Dialog", import: "Modal" },
      { name: "Navbar",     description: "Navigation", import: "Navbar" },
      { name: "Pagination", description: "Nav", import: "Pagination" },
      { name: "Popover",    description: "Floating", import: "Popover" },
      { name: "Progress",   description: "Progress", import: "Progress" },
      { name: "Radio",      description: "Single-choice", import: "RadioGroup" },
      { name: "Select",     description: "Dropdown", import: "Select" },
      { name: "Skeleton",   description: "Loading", import: "Skeleton" },
      { name: "Slider",     description: "Range", import: "Slider" },
      { name: "Snippet",    description: "Code clip", import: "Snippet" },
      { name: "Switch",     description: "Toggle", import: "Switch" },
      { name: "Table",      description: "Data", import: "Table" },
      { name: "Tabs",       description: "Tabs", import: "Tabs" },
      { name: "Textarea",   description: "Input area", import: "Textarea" },
      { name: "Tooltip",    description: "Tip", import: "Tooltip" },
      { name: "User",       description: "Profile", import: "User" },
    ],
  },

  daisyui: {
    name: "daisyUI",
    strategy: "npm-plugin",
    packages: ["daisyui"],
    devDep: true,
    importPrefix: null,
    docsURL: "https://daisyui.com",
    setupNote: 'Add "daisyui" to plugins: [] in tailwind.config.js',
    components: [
      { name: "button",      description: "Button classes", className: "btn" },
      { name: "card",        description: "Card container", className: "card" },
      { name: "navbar",      description: "Navigation bar", className: "navbar" },
      { name: "drawer",      description: "Side panel", className: "drawer" },
      { name: "modal",       description: "Modal box", className: "modal" },
      { name: "alert",       description: "Alert banner", className: "alert" },
      { name: "badge",       description: "Badge indicator", className: "badge" },
      { name: "dropdown",    description: "Dropdown panel", className: "dropdown" },
      { name: "menu",        description: "Menu list", className: "menu" },
      { name: "progress",    description: "Progress bar", className: "progress" },
      { name: "tabs",        description: "Tab container", className: "tabs" },
      { name: "table",       description: "Data table", className: "table" },
      { name: "toggle",      description: "Switch control", className: "toggle" },
      { name: "tooltip",     description: "Hover hint", className: "tooltip" },
      { name: "input",       description: "Text field", className: "input" },
      { name: "select",      description: "Pick list", className: "select" },
      { name: "skeleton",    description: "Loading state", className: "skeleton" },
      { name: "footer",      description: "Bottom bar", className: "footer" },
    ],
  },

  antd: {
    name: "Ant Design",
    strategy: "npm",
    packages: ["antd"],
    importPrefix: "antd",
    docsURL: "https://ant.design",
    components: [
      { name: "Button",       description: "Action button", import: "Button" },
      { name: "Table",        description: "Data Grid", import: "Table" },
      { name: "Form",         description: "Form wrapper", import: "Form" },
      { name: "Input",        description: "Text field", import: "Input" },
      { name: "Select",       description: "Dropdown", import: "Select" },
      { name: "Modal",        description: "Dialog", import: "Modal" },
      { name: "Card",         description: "Container", import: "Card" },
      { name: "Tabs",         description: "Sections", import: "Tabs" },
      { name: "Menu",         description: "Navigation", import: "Menu" },
      { name: "Drawer",       description: "Sidebar", import: "Drawer" },
      { name: "Alert",        description: "Banner", import: "Alert" },
      { name: "Avatar",       description: "Circle image", import: "Avatar" },
      { name: "Badge",        description: "Dot/Number", import: "Badge" },
      { name: "Breadcrumb",   description: "Path trail", import: "Breadcrumb" },
      { name: "Checkbox",     description: "Box toggle", import: "Checkbox" },
      { name: "DatePicker",   description: "Calendar", import: "DatePicker" },
      { name: "Dropdown",     description: "Hover list", import: "Dropdown" },
      { name: "Pagination",   description: "Pages", import: "Pagination" },
      { name: "Progress",     description: "Bar/Circle", import: "Progress" },
      { name: "Radio",        description: "Single pick", import: "Radio" },
      { name: "Slider",       description: "Range bar", import: "Slider" },
      { name: "Spin",         description: "Loading", import: "Spin" },
      { name: "Switch",       description: "On/Off", import: "Switch" },
      { name: "Tag",          description: "Label", import: "Tag" },
      { name: "Tooltip",      description: "Pop hint", import: "Tooltip" },
      { name: "Typography",   description: "Text block", import: "Typography" },
      { name: "Upload",       description: "File pick", import: "Upload" },
    ],
  },

  mantine: {
    name: "Mantine UI",
    strategy: "npm",
    packages: ["@mantine/core", "@mantine/hooks"],
    importPrefix: "@mantine/core",
    docsURL: "https://mantine.dev",
    components: [
      { name: "Accordion",    description: "Collapsible", import: "Accordion" },
      { name: "ActionIcon",   description: "Icon btn", import: "ActionIcon" },
      { name: "Alert",        description: "Banner", import: "Alert" },
      { name: "Avatar",       description: "Profile", import: "Avatar" },
      { name: "Badge",        description: "Indicator", import: "Badge" },
      { name: "Button",       description: "Action", import: "Button" },
      { name: "Card",         description: "Container", import: "Card" },
      { name: "Checkbox",     description: "Toggle", import: "Checkbox" },
      { name: "Container",    description: "Centered", import: "Container" },
      { name: "Drawer",       description: "Sidebar", import: "Drawer" },
      { name: "Grid",         description: "Layout", import: "Grid" },
      { name: "Group",        description: "Spacing", import: "Group" },
      { name: "Input",        description: "Field", import: "Input" },
      { name: "Menu",         description: "List", import: "Menu" },
      { name: "Modal",        description: "Dialog", import: "Modal" },
      { name: "Pagination",   description: "Nav", import: "Pagination" },
      { name: "Progress",     description: "Bar", import: "Progress" },
      { name: "Radio",        description: "Pick", import: "Radio" },
      { name: "Select",       description: "Drop", import: "Select" },
      { name: "Skeleton",     description: "Load", import: "Skeleton" },
      { name: "Slider",       description: "Range", import: "Slider" },
      { name: "Stack",        description: "Vertical", import: "Stack" },
      { name: "Switch",       description: "Toggle", import: "Switch" },
      { name: "Table",        description: "Data", import: "Table" },
      { name: "Tabs",         description: "Tabs", import: "Tabs" },
      { name: "TextInput",    description: "Text", import: "TextInput" },
      { name: "Textarea",     description: "Area", import: "Textarea" },
      { name: "Tooltip",      description: "Tip", import: "Tooltip" },
    ],
  },
};

export const ALIASES = {
  "shadcn":    "shadcn",
  "shadcnui":  "shadcn",
  "mui":       "mui",
  "material":  "mui",
  "chakra":    "chakra",
  "chakraui":  "chakra",
  "nextui":    "nextui",
  "daisyui":   "daisyui",
  "daisy":     "daisyui",
  "antd":      "antd",
  "mantine":   "mantine",
};

export function resolveLibrary(input) {
  const key = input.toLowerCase().replace(/[\s\-_\/]/g, "");
  return ALIASES[key] || null;
}
